### ISSUE TITLE
Feature: Hide icon tray

### ISSUE THREAD

**Issue by cdecompilador** [carlalbrecht/snip-and-autosave#1]
First, thanks for the tool, its amazing does exactly what I needed, it would also be great to have an option to hide also the icon on the icon tray and show it again when executed again the program, this would require to check if an instance of the program is already running

**Comment by carlalbrecht** [comment]
I think this would be a good feature to add as well. Do you want the icon to stay hidden even when the program restarts (e.g. it is set to start on boot, and you restart your computer), but only be shown again if the program is started whilst it's already running, or do you want it to only be hidden for the current session?

**Comment by cdecompilador** [comment]
yeah, hidden on autostart would be good
